name: Build

on:
  push:
    branches: [ master ]
    tags: v*
  pull_request:
    branches: [ master ]

jobs:
    Build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Setup dotnet
              uses: actions/setup-dotnet@v1
              with:
                  dotnet-version: 5.0.x
            - name: Acquire SIRA References
              uses: ProjectSIRA/download-sira-stripped@1.0.0
              with:
                  manifest: ${{ github.workspace }}/Source/manifest.json
                  sira-server-code: ${{ secrets.SIRA_SERVER_CODE }}
            - name: Download Mod Dependencies
              uses: Goobwabber/download-beatmods-deps@1.2
              with:
                  manifest: ${{ github.workspace }}/Source/manifest.json
            - name: Build
              id: Build
              env: 
                  FrameworkPathOverride: /usr/lib/mono/4.8-api
              run: dotnet build --configuration Release
            - name: GitStatus
              run: git status
            - name: Echo Filename
              run: echo $BUILDTEXT \($ASSEMBLYNAME\)
              env:
                  BUILDTEXT: Filename=${{ steps.Build.outputs.filename }}
                  ASSEMBLYNAME: AssemblyName=${{ steps.Build.outputs.assemblyname }}
            - name: Upload Artifact
              uses: actions/upload-artifact@v1
              with:
                  name: ${{ steps.Build.outputs.filename }}
                  path: ${{ steps.Build.outputs.artifactpath }}
            - name: Release
              uses: softprops/action-gh-release@v1
              if: startsWith(github.ref, 'refs/tags/')
              with:
                files: ./${{ steps.Build.outputs.filename }}.zip
              env: 
                GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
